name: .NET Core Deploy to IIS

on: 
  # push:
    # branches:
    #   - "self-hosted"
  workflow_dispatch:

jobs:
  build-and-deploy:

    runs-on: [self-hosted,PSL-APP-VM3]
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.0.100
    
    # dotnet build and publish
    - name: Build with dotnet
      run: dotnet build --configuration Release .\eVat-IdentityServer

    - name: dotnet publish 
      run: |
        dotnet publish -c Release -o dotnetcorewebapp .\eVat-IdentityServer

    - name: Deploy to IIS
      run: |
        iisreset /stop
        Copy-Item ./dotnetcorewebapp/* C:/inetpub/wwwroot/eVat-IdentityServer -Recurse -Force
        iisreset /start
    
    - name: Curl the website as a smoke test
      run: curl http://localhost/eVat-IdentityServer
